#Anything that is optional which you are not using, just delete that line. You can also delete any of the '#comments'
 
modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory
license="All rights reserved" #mandatory https://choosealicense.com/
 
[[mods]] #mandatory
modId="easywiring" #mandatory
version="1.0" #mandatory
displayName="Easy Wiring" #mandatory
authors="OcWebb" #optional
description='''
A mod to make placing pipes easy
''' #mandatory